// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jksjyhqelduduxmkcuae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imprc2p5aHFlbGR1ZHV4bWtjdWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4OTgyNTQsImV4cCI6MjA1NzQ3NDI1NH0.9GJUCP13uxWPFXg3x8XO0AVqU5qKATv-N9tjTIPiI_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);